name: Run tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
    GO_VERSION: "~1.21"

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4

      - name: Set up Go
        uses: actions/setup-go@0c52d547c9bc32b1aa3301fd7a9cb496313a4491 # v5
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Run coverage
        run: go test ./... -race -coverprofile=coverage.out -covermode=atomic
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@eaaf4bedf32dbdc6b720b63067d99c4d77d6047d # v3

      # - name: Fmt Test
      #   run: fmtFiles=$(make fmt); if [ "$fmtFiles" != "" ];then exit 1; fi

